// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BudgetCreate = {
    amount?: number;
    month: number;
    year: number;
    category_id?: (string | null);
};

export type BudgetPublic = {
    amount?: number;
    month: number;
    year: number;
    id: string;
    category_id: (string | null);
    owner_id: string;
    created_at?: (string | null);
};

export type BudgetsWithCategoryPublic = {
    data: Array<BudgetWithCategory>;
    count: number;
};

export type BudgetUpdate = {
    amount?: (number | null);
    category_id?: (string | null);
};

export type BudgetWithCategory = {
    id: string;
    amount: number;
    month: number;
    year: number;
    category_id: (string | null);
    category_name: (string | null);
    category_icon: (string | null);
    category_color: (string | null);
    spent: number;
    remaining: number;
    percentage: number;
};

export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

export type CategoryCreate = {
    name: string;
    type?: TransactionType;
    icon?: (string | null);
    color?: (string | null);
    description?: (string | null);
};

export type CategoryMonthlySummaries = {
    income_categories: Array<CategoryMonthlySummary>;
    expense_categories: Array<CategoryMonthlySummary>;
    total_income: number;
    total_expense: number;
};

export type CategoryMonthlySummary = {
    category_id: string;
    category_name: string;
    category_icon: (string | null);
    category_color: (string | null);
    type: TransactionType;
    total_amount: number;
    transaction_count: number;
    percentage: number;
};

export type CategoryPublic = {
    name: string;
    type?: TransactionType;
    icon?: (string | null);
    color?: (string | null);
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type CategoryUpdate = {
    name?: (string | null);
    type?: (TransactionType | null);
    icon?: (string | null);
    color?: (string | null);
    description?: (string | null);
};

export type DailyTrend = {
    date: string;
    income: number;
    expense: number;
    balance: number;
};

export type DailyTrends = {
    days: Array<DailyTrend>;
};

export type Frequency = 'daily' | 'weekly' | 'monthly';

export type HabitCalendar = {
    year: number;
    month: number;
    days: Array<HabitCalendarDay>;
};

export type HabitCalendarDay = {
    date: string;
    total_count: number;
    completed_count: number;
    habit_ids: Array<(string)>;
    record_ids: {
        [key: string]: (string);
    };
};

export type HabitCreate = {
    name: string;
    frequency?: Frequency;
    target_count?: number;
    description?: (string | null);
};

export type HabitPublic = {
    name: string;
    frequency?: Frequency;
    target_count?: number;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type HabitRecordCreate = {
    count?: number;
    note?: (string | null);
    habit_id: string;
    check_date: string;
};

export type HabitRecordPublic = {
    count?: number;
    note?: (string | null);
    id: string;
    habit_id: string;
    owner_id: string;
    check_date: string;
    created_at?: (string | null);
};

export type HabitRecordsPublic = {
    data: Array<HabitRecordPublic>;
    count: number;
};

export type HabitsPublic = {
    data: Array<HabitPublic>;
    count: number;
};

export type HabitStatistics = {
    total_habits: number;
    total_checks_last_30_days: number;
    average_checks_per_day: number;
    most_active_day: (string | null);
    streak_days: number;
};

export type HabitTrend = {
    days: Array<HabitTrendDay>;
};

export type HabitTrendDay = {
    date: string;
    completed_count: number;
    total_habits: number;
};

export type HabitUpdate = {
    name?: (string | null);
    frequency?: (Frequency | null);
    target_count?: (number | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
};

export type Message = {
    message: string;
};

export type MonthlySummary = {
    month: number;
    year: number;
    total_income: number;
    total_expense: number;
    balance: number;
    income_count: number;
    expense_count: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TransactionCreate = {
    amount?: number;
    type?: TransactionType;
    description?: (string | null);
    transaction_date?: (string | null);
    category_id: string;
};

export type TransactionPublic = {
    amount?: number;
    type?: TransactionType;
    description?: (string | null);
    transaction_date?: (string | null);
    id: string;
    category_id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type TransactionsWithCategoryPublic = {
    data: Array<TransactionWithCategory>;
    count: number;
};

export type TransactionType = 'income' | 'expense';

export type TransactionUpdate = {
    amount?: (number | null);
    type?: (TransactionType | null);
    description?: (string | null);
    category_id?: (string | null);
    transaction_date?: (string | null);
};

export type TransactionWithCategory = {
    id: string;
    amount: number;
    type: TransactionType;
    description: (string | null);
    transaction_date: (string | null);
    category_id: string;
    category_name: (string | null);
    category_icon: (string | null);
    category_color: (string | null);
    created_at: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type YearlySummary = {
    year: number;
    total_income: number;
    total_expense: number;
    balance: number;
    monthly_breakdown: Array<{
        [key: string]: (number);
    }>;
};

export type BudgetsReadBudgetsData = {
    month?: (number | null);
    year?: (number | null);
};

export type BudgetsReadBudgetsResponse = (BudgetsWithCategoryPublic);

export type BudgetsCreateBudgetData = {
    requestBody: BudgetCreate;
};

export type BudgetsCreateBudgetResponse = (BudgetPublic);

export type BudgetsReadBudgetData = {
    id: string;
};

export type BudgetsReadBudgetResponse = (BudgetWithCategory);

export type BudgetsUpdateBudgetData = {
    id: string;
    requestBody: BudgetUpdate;
};

export type BudgetsUpdateBudgetResponse = (BudgetPublic);

export type BudgetsDeleteBudgetData = {
    id: string;
};

export type BudgetsDeleteBudgetResponse = (Message);

export type BudgetsCheckOverbudgetData = {
    month?: (number | null);
    year?: (number | null);
};

export type BudgetsCheckOverbudgetResponse = (unknown);

export type CategoriesReadCategoriesData = {
    limit?: number;
    skip?: number;
    type?: (TransactionType | null);
};

export type CategoriesReadCategoriesResponse = (CategoriesPublic);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesReadCategoryData = {
    id: string;
};

export type CategoriesReadCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryData = {
    id: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesDeleteCategoryData = {
    id: string;
};

export type CategoriesDeleteCategoryResponse = (Message);

export type HabitRecordsReadHabitRecordsData = {
    endDate?: (string | null);
    habitId?: (string | null);
    limit?: number;
    skip?: number;
    startDate?: (string | null);
};

export type HabitRecordsReadHabitRecordsResponse = (HabitRecordsPublic);

export type HabitRecordsCreateHabitRecordData = {
    requestBody: HabitRecordCreate;
};

export type HabitRecordsCreateHabitRecordResponse = (HabitRecordPublic);

export type HabitRecordsGetHabitCalendarData = {
    month: number;
    year: number;
};

export type HabitRecordsGetHabitCalendarResponse = (HabitCalendar);

export type HabitRecordsGetHabitTrendData = {
    days?: number;
};

export type HabitRecordsGetHabitTrendResponse = (HabitTrend);

export type HabitRecordsGetHabitStatisticsResponse = (HabitStatistics);

export type HabitRecordsDeleteHabitRecordData = {
    id: string;
};

export type HabitRecordsDeleteHabitRecordResponse = (Message);

export type HabitsReadHabitsData = {
    limit?: number;
    skip?: number;
};

export type HabitsReadHabitsResponse = (HabitsPublic);

export type HabitsCreateHabitData = {
    requestBody: HabitCreate;
};

export type HabitsCreateHabitResponse = (HabitPublic);

export type HabitsReadHabitData = {
    id: string;
};

export type HabitsReadHabitResponse = (HabitPublic);

export type HabitsUpdateHabitData = {
    id: string;
    requestBody: HabitUpdate;
};

export type HabitsUpdateHabitResponse = (HabitPublic);

export type HabitsDeleteHabitData = {
    id: string;
};

export type HabitsDeleteHabitResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TransactionsReadTransactionsData = {
    categoryId?: (string | null);
    endDate?: (string | null);
    limit?: number;
    maxAmount?: (number | null);
    minAmount?: (number | null);
    search?: (string | null);
    skip?: number;
    startDate?: (string | null);
    type?: (TransactionType | null);
};

export type TransactionsReadTransactionsResponse = (TransactionsWithCategoryPublic);

export type TransactionsCreateTransactionData = {
    requestBody: TransactionCreate;
};

export type TransactionsCreateTransactionResponse = (TransactionPublic);

export type TransactionsReadTransactionData = {
    id: string;
};

export type TransactionsReadTransactionResponse = (TransactionWithCategory);

export type TransactionsUpdateTransactionData = {
    id: string;
    requestBody: TransactionUpdate;
};

export type TransactionsUpdateTransactionResponse = (TransactionPublic);

export type TransactionsDeleteTransactionData = {
    id: string;
};

export type TransactionsDeleteTransactionResponse = (Message);

export type TransactionsGetMonthlySummaryData = {
    month?: (number | null);
    year?: (number | null);
};

export type TransactionsGetMonthlySummaryResponse = (MonthlySummary);

export type TransactionsGetCategoryMonthlySummaryData = {
    month?: (number | null);
    year?: (number | null);
};

export type TransactionsGetCategoryMonthlySummaryResponse = (CategoryMonthlySummaries);

export type TransactionsGetDailyTrendData = {
    days?: number;
};

export type TransactionsGetDailyTrendResponse = (DailyTrends);

export type TransactionsGetYearlySummaryData = {
    year?: (number | null);
};

export type TransactionsGetYearlySummaryResponse = (YearlySummary);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);