"""Add checkin record model

Revision ID: 000000000002
Revises: 000000000001
Create Date: 2026-04-17 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '000000000002'
down_revision = '000000000001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'checkinrecord',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('checkin_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('habit_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ['habit_id'],
            ['habit.id'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_checkinrecord_checkin_date'),
        'checkinrecord',
        ['checkin_date'],
        unique=False,
    )
    op.create_index(
        op.f('ix_checkinrecord_habit_id'),
        'checkinrecord',
        ['habit_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_checkinrecord_user_id'),
        'checkinrecord',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkinrecord_user_id'), table_name='checkinrecord')
    op.drop_index(op.f('ix_checkinrecord_habit_id'), table_name='checkinrecord')
    op.drop_index(op.f('ix_checkinrecord_checkin_date'), table_name='checkinrecord')
    op.drop_table('checkinrecord')
    # ### end Alembic commands ###
