/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTransactionsRouteImport } from './routes/_layout/transactions'
import { Route as LayoutTasksRouteImport } from './routes/_layout/tasks'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRecycleRouteImport } from './routes/_layout/recycle'
import { Route as LayoutPomodoroRouteImport } from './routes/_layout/pomodoro'
import { Route as LayoutLogsRouteImport } from './routes/_layout/logs'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutHabitsRouteImport } from './routes/_layout/habits'
import { Route as LayoutHabitStatsRouteImport } from './routes/_layout/habit-stats'
import { Route as LayoutHabitCalendarRouteImport } from './routes/_layout/habit-calendar'
import { Route as LayoutFinanceStatsRouteImport } from './routes/_layout/finance-stats'
import { Route as LayoutFilesRouteImport } from './routes/_layout/files'
import { Route as LayoutCategoriesRouteImport } from './routes/_layout/categories'
import { Route as LayoutCalendarRouteImport } from './routes/_layout/calendar'
import { Route as LayoutBudgetsRouteImport } from './routes/_layout/budgets'
import { Route as LayoutArticlesRouteImport } from './routes/_layout/articles'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutArticlesIndexRouteImport } from './routes/_layout/articles.index'
import { Route as LayoutArticlesIdRouteImport } from './routes/_layout/articles.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTransactionsRoute = LayoutTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksRoute = LayoutTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecycleRoute = LayoutRecycleRouteImport.update({
  id: '/recycle',
  path: '/recycle',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPomodoroRoute = LayoutPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLogsRoute = LayoutLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHabitsRoute = LayoutHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHabitStatsRoute = LayoutHabitStatsRouteImport.update({
  id: '/habit-stats',
  path: '/habit-stats',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHabitCalendarRoute = LayoutHabitCalendarRouteImport.update({
  id: '/habit-calendar',
  path: '/habit-calendar',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFinanceStatsRoute = LayoutFinanceStatsRouteImport.update({
  id: '/finance-stats',
  path: '/finance-stats',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFilesRoute = LayoutFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesRoute = LayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalendarRoute = LayoutCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBudgetsRoute = LayoutBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutArticlesRoute = LayoutArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutArticlesIndexRoute = LayoutArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutArticlesRoute,
} as any)
const LayoutArticlesIdRoute = LayoutArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/articles': typeof LayoutArticlesRouteWithChildren
  '/budgets': typeof LayoutBudgetsRoute
  '/calendar': typeof LayoutCalendarRoute
  '/categories': typeof LayoutCategoriesRoute
  '/files': typeof LayoutFilesRoute
  '/finance-stats': typeof LayoutFinanceStatsRoute
  '/habit-calendar': typeof LayoutHabitCalendarRoute
  '/habit-stats': typeof LayoutHabitStatsRoute
  '/habits': typeof LayoutHabitsRoute
  '/items': typeof LayoutItemsRoute
  '/logs': typeof LayoutLogsRoute
  '/pomodoro': typeof LayoutPomodoroRoute
  '/recycle': typeof LayoutRecycleRoute
  '/settings': typeof LayoutSettingsRoute
  '/tasks': typeof LayoutTasksRoute
  '/transactions': typeof LayoutTransactionsRoute
  '/articles/$id': typeof LayoutArticlesIdRoute
  '/articles/': typeof LayoutArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/budgets': typeof LayoutBudgetsRoute
  '/calendar': typeof LayoutCalendarRoute
  '/categories': typeof LayoutCategoriesRoute
  '/files': typeof LayoutFilesRoute
  '/finance-stats': typeof LayoutFinanceStatsRoute
  '/habit-calendar': typeof LayoutHabitCalendarRoute
  '/habit-stats': typeof LayoutHabitStatsRoute
  '/habits': typeof LayoutHabitsRoute
  '/items': typeof LayoutItemsRoute
  '/logs': typeof LayoutLogsRoute
  '/pomodoro': typeof LayoutPomodoroRoute
  '/recycle': typeof LayoutRecycleRoute
  '/settings': typeof LayoutSettingsRoute
  '/tasks': typeof LayoutTasksRoute
  '/transactions': typeof LayoutTransactionsRoute
  '/': typeof LayoutIndexRoute
  '/articles/$id': typeof LayoutArticlesIdRoute
  '/articles': typeof LayoutArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/articles': typeof LayoutArticlesRouteWithChildren
  '/_layout/budgets': typeof LayoutBudgetsRoute
  '/_layout/calendar': typeof LayoutCalendarRoute
  '/_layout/categories': typeof LayoutCategoriesRoute
  '/_layout/files': typeof LayoutFilesRoute
  '/_layout/finance-stats': typeof LayoutFinanceStatsRoute
  '/_layout/habit-calendar': typeof LayoutHabitCalendarRoute
  '/_layout/habit-stats': typeof LayoutHabitStatsRoute
  '/_layout/habits': typeof LayoutHabitsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/logs': typeof LayoutLogsRoute
  '/_layout/pomodoro': typeof LayoutPomodoroRoute
  '/_layout/recycle': typeof LayoutRecycleRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tasks': typeof LayoutTasksRoute
  '/_layout/transactions': typeof LayoutTransactionsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/articles/$id': typeof LayoutArticlesIdRoute
  '/_layout/articles/': typeof LayoutArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/articles'
    | '/budgets'
    | '/calendar'
    | '/categories'
    | '/files'
    | '/finance-stats'
    | '/habit-calendar'
    | '/habit-stats'
    | '/habits'
    | '/items'
    | '/logs'
    | '/pomodoro'
    | '/recycle'
    | '/settings'
    | '/tasks'
    | '/transactions'
    | '/articles/$id'
    | '/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/budgets'
    | '/calendar'
    | '/categories'
    | '/files'
    | '/finance-stats'
    | '/habit-calendar'
    | '/habit-stats'
    | '/habits'
    | '/items'
    | '/logs'
    | '/pomodoro'
    | '/recycle'
    | '/settings'
    | '/tasks'
    | '/transactions'
    | '/'
    | '/articles/$id'
    | '/articles'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/articles'
    | '/_layout/budgets'
    | '/_layout/calendar'
    | '/_layout/categories'
    | '/_layout/files'
    | '/_layout/finance-stats'
    | '/_layout/habit-calendar'
    | '/_layout/habit-stats'
    | '/_layout/habits'
    | '/_layout/items'
    | '/_layout/logs'
    | '/_layout/pomodoro'
    | '/_layout/recycle'
    | '/_layout/settings'
    | '/_layout/tasks'
    | '/_layout/transactions'
    | '/_layout/'
    | '/_layout/articles/$id'
    | '/_layout/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transactions': {
      id: '/_layout/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof LayoutTransactionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks': {
      id: '/_layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recycle': {
      id: '/_layout/recycle'
      path: '/recycle'
      fullPath: '/recycle'
      preLoaderRoute: typeof LayoutRecycleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pomodoro': {
      id: '/_layout/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof LayoutPomodoroRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/logs': {
      id: '/_layout/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LayoutLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/habits': {
      id: '/_layout/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof LayoutHabitsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/habit-stats': {
      id: '/_layout/habit-stats'
      path: '/habit-stats'
      fullPath: '/habit-stats'
      preLoaderRoute: typeof LayoutHabitStatsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/habit-calendar': {
      id: '/_layout/habit-calendar'
      path: '/habit-calendar'
      fullPath: '/habit-calendar'
      preLoaderRoute: typeof LayoutHabitCalendarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/finance-stats': {
      id: '/_layout/finance-stats'
      path: '/finance-stats'
      fullPath: '/finance-stats'
      preLoaderRoute: typeof LayoutFinanceStatsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/files': {
      id: '/_layout/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof LayoutFilesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories': {
      id: '/_layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calendar': {
      id: '/_layout/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof LayoutCalendarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/budgets': {
      id: '/_layout/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof LayoutBudgetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/articles': {
      id: '/_layout/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof LayoutArticlesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/articles/': {
      id: '/_layout/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof LayoutArticlesIndexRouteImport
      parentRoute: typeof LayoutArticlesRoute
    }
    '/_layout/articles/$id': {
      id: '/_layout/articles/$id'
      path: '/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof LayoutArticlesIdRouteImport
      parentRoute: typeof LayoutArticlesRoute
    }
  }
}

interface LayoutArticlesRouteChildren {
  LayoutArticlesIdRoute: typeof LayoutArticlesIdRoute
  LayoutArticlesIndexRoute: typeof LayoutArticlesIndexRoute
}

const LayoutArticlesRouteChildren: LayoutArticlesRouteChildren = {
  LayoutArticlesIdRoute: LayoutArticlesIdRoute,
  LayoutArticlesIndexRoute: LayoutArticlesIndexRoute,
}

const LayoutArticlesRouteWithChildren = LayoutArticlesRoute._addFileChildren(
  LayoutArticlesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutArticlesRoute: typeof LayoutArticlesRouteWithChildren
  LayoutBudgetsRoute: typeof LayoutBudgetsRoute
  LayoutCalendarRoute: typeof LayoutCalendarRoute
  LayoutCategoriesRoute: typeof LayoutCategoriesRoute
  LayoutFilesRoute: typeof LayoutFilesRoute
  LayoutFinanceStatsRoute: typeof LayoutFinanceStatsRoute
  LayoutHabitCalendarRoute: typeof LayoutHabitCalendarRoute
  LayoutHabitStatsRoute: typeof LayoutHabitStatsRoute
  LayoutHabitsRoute: typeof LayoutHabitsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutLogsRoute: typeof LayoutLogsRoute
  LayoutPomodoroRoute: typeof LayoutPomodoroRoute
  LayoutRecycleRoute: typeof LayoutRecycleRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTasksRoute: typeof LayoutTasksRoute
  LayoutTransactionsRoute: typeof LayoutTransactionsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutArticlesRoute: LayoutArticlesRouteWithChildren,
  LayoutBudgetsRoute: LayoutBudgetsRoute,
  LayoutCalendarRoute: LayoutCalendarRoute,
  LayoutCategoriesRoute: LayoutCategoriesRoute,
  LayoutFilesRoute: LayoutFilesRoute,
  LayoutFinanceStatsRoute: LayoutFinanceStatsRoute,
  LayoutHabitCalendarRoute: LayoutHabitCalendarRoute,
  LayoutHabitStatsRoute: LayoutHabitStatsRoute,
  LayoutHabitsRoute: LayoutHabitsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutLogsRoute: LayoutLogsRoute,
  LayoutPomodoroRoute: LayoutPomodoroRoute,
  LayoutRecycleRoute: LayoutRecycleRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTasksRoute: LayoutTasksRoute,
  LayoutTransactionsRoute: LayoutTransactionsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
